---
title: "p8105_hw1_lmp2234"
author: "Lisa Pardee"
date: "2024-09-21"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Problem 1

```{r}
library(palmerpenguins)

data("penguins",package="palmerpenguins")

row_num<-nrow(penguins)
col_num<-ncol(penguins)

mean_flipper<-mean(penguins$flipper_length_mm, na.rm = TRUE)

```

**The penguins data set contains information about different species of penguins and their characteristics. The variables include species, island, bill length, bill depth, flipper length, body mass index, sex, and year. The dataset has `r row_num` rows and `r col_num` columns. The mean flipper length is `r mean_flipper` mm.** 


```{r}
library(tidyverse)

set.seed(1234)

ggplot(penguins, aes(x=bill_length_mm, y = flipper_length_mm, color = species)) + 
  geom_point() +
  labs(title = "Flipper length vs Bill Length Scatterplot", 
      x = "Bill Length (mm)",
      y = "Flipper Length (mm)")

ggsave("scatter_plot.pdf", height = 4, width =6)

```

